### ISSUE TITLE
Bundle: Scala compilation issues after upgrading to 3.9.0

### ISSUE THREAD

**Issue by mcopjan** [gatling/gatling#4368]
Hi, can someone please shed some light on the following? 
I am running my gatling tests from a docker container that is build on openjdk:11-jdk-slim-bullseye
After upgrade from 3.8.4 -> 3.9.0 it looks like my scala class is no longer compiled successfully. Not really familiar with scala hence any help would be appreciated.

`docker run -v $(pwd)/user-files/:/src/gatling/user-files gatlingtest2:latest
GATLING_HOME is set to /src/gatling
10:30:49.056 [WARN ] i.g.c.ZincCompiler$ - -target is deprecated: Use -release instead to compile against the correct platform API.
10:31:33.116 [ERROR] i.g.c.ZincCompiler$ - ## Exception when compiling 1 sources to /src/gatling/target/test-classes
10:31:33.124 [ERROR] i.g.c.ZincCompiler$ - Compilation crashed
java.lang.StackOverflowError: null
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5630)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5080)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5110)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5991)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:739)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:821)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6047)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$41(Typers.scala:5078)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
`

**Comment by slandelle** [comment]
Hi,

This is already fixed in https://github.com/gatling/gatling-enterprise-plugin-commons/commit/df5b6e4c00fecdf5cbc12579b604f7c0d6104e51 and only affects the bundle, not other launchers.
Fix will be shipped in 3.9.1.

**Comment by slandelle** [comment]
@mcopjan Gatling 3.9.1 is out.

**Comment by mcopjan** [comment]
@slandelle thanks, appreciate that

**Comment by mcopjan** [comment]
Still seeing 3.9.0 in the download link but I guess it might take some time to update your CDN

**Comment by slandelle** [comment]
That, and that most of the company is attending a company event today. But the update should be visible soon.
